#!/usr/bin/env python3
"""
Generate release notes with archive_override examples for all packaged tools.
"""

import json
import sys
from pathlib import Path

def main():
    if len(sys.argv) != 4:
        print("Usage: generate_release_notes.py <packages_dir> <tag_name> <repository>", file=sys.stderr)
        sys.exit(1)

    packages_dir = Path(sys.argv[1])
    tag_name = sys.argv[2]
    repository = sys.argv[3]

    # Load packages info
    packages_json = packages_dir / 'packages.json'
    with open(packages_json) as f:
        packages = json.load(f)

    # Generate release notes
    notes = f"""Automated CI release for tools with git submodules.

---

## 📦 Packaged Tools

This release contains archive snapshots of the following tools **with their submodules included**:

"""

    for pkg in packages:
        notes += f"- **{pkg['module_name']}** (commit `{pkg['commit'][:7]}`)\n"

    notes += f"""

---

## 🚀 Usage in Your Project

Instead of using `git_override` (which is slow for CI), you can use `archive_override` with these pre-packaged archives:

```bzl
"""

    for pkg in packages:
        url = f"https://github.com/{repository}/releases/download/{tag_name}/{pkg['tarball_name']}"
        notes += f"""
# {pkg['module_name']} - archive with submodules included
bazel_dep(name = "{pkg['module_name']}", version = "1.0.0")
archive_override(
    module_name = "{pkg['module_name']}",
    urls = ["{url}"],
    strip_prefix = "{pkg['strip_prefix']}",
    integrity = "{pkg['integrity']}",
)

"""

    notes += """```

---

## 📝 Notes

- All archives include **initialized submodules**
- These archives are suitable for CI/CD environments where git operations are slow
- For development, you may prefer using `git_override` for easier iteration

## ⚙️ How This Release Was Generated

1. Scanned `MODULE.bazel` for `git_override` declarations
2. Checked each repository for `.gitmodules` file
3. Cloned repositories with `--recursive` submodule initialization
4. Created tarballs excluding `.git` directories
5. Calculated `sha256-base64` integrity hashes for Bazel bzlmod

---

**Generated by** [rules_hdl CI](https://github.com/{repository}/actions)
"""

    print(notes)

if __name__ == '__main__':
    main()
